version: '2.1'

services:
  octobercms:
    image: aspendigital/octobercms:php7.1-apache
    ports:
      - 80:80
    environment:
      TZ: ${TZ:-America/Denver}
    volumes:
      - ./docker-php.ini:/usr/local/etc/php/conf.d/docker-compose-php.ini
      - ./config/docker:/var/www/html/config/docker
      - ./plugins:/var/www/html/plugins
      - ./themes:/var/www/html/themes

      # - ./.env:/var/www/html/.env
      # - ./storage/app:/var/www/html/storage/app
      # - ./storage/logs:/var/www/html/storage/logs
      # - ./storage/database.sqlite:/var/www/html/storage/database.sqlite
