version: '2.1'

services:
  nginx:
    image: nginx:latest
    depends_on:
      - octobercms
    environment:
      TZ: ${TZ:-America/Denver}
    ports:
      - 80:80
    volumes:
      - ./docker-nginx.conf:/etc/nginx/conf.d/default.conf
      # Note: The fastcgi_pass name must match the service name for PHP (octobercms)
    volumes_from:
      - octobercms

  octobercms:
    image: aspendigital/octobercms:php7.1-fpm
    environment:
      TZ: ${TZ:-America/Denver}
    volumes:
      - /var/www/html
      # share with nginx - Run `docker-compose down -v` to remove the shared volume

      - ./docker-php.ini:/usr/local/etc/php/conf.d/docker-compose-php.ini
      - ./config/docker:/var/www/html/config/docker
      - ./plugins:/var/www/html/plugins
      - ./themes:/var/www/html/themes

      # - ./.env:/var/www/html/.env
      # - ./storage/app:/var/www/html/storage/app
      # - ./storage/logs:/var/www/html/storage/logs
      # - ./storage/database.sqlite:/var/www/html/storage/database.sqlite
